version: "3.9"

services:
    # add database first
    database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
        image: postgres
        container_name: database_unittest
        restart: always
        ports:
            - 5432:5432 #usual port for postgres
            - 9229:9229
        environment:
            - POSTGRES_USER=postgres # docker
            - POSTGRES_PASSWORD=docker # ignite
            - POSTGRES_DB=fin_api # rentx
        volumes:
            - pgdata:/data/postgres
        #network_mode: host
    app:
        build: .
        container_name: fin_api_unittest
        restart: always
        ports:
            - 3333:3333
            - 9229:9229
        volumes:
            - .:/usr/app
        #network_mode: host
        links:
            - database
        depends_on:
            - database

volumes:
    pgdata: #reference for 'volumes' above
        driver: local
